In [3]:
import numpy as np

## Calculates the percentage of calories for carbs, protein and fats for apples, beefs eggs and potatoes

In [12]:
#A holds the calories of different fruits 
A = np.array([[56.0, 0.0, 4.4, 86.0],[1.2, 104.0, 52.0, 8.0],[1.8,135.0,99.0,0.9]])
print(A)

[[ 56.    0.    4.4  86. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [11]:
#Sum the calories down each column
cal = A.sum(axis = 0)
print(cal)

[ 59.  239.  155.4  94.9]


In [15]:
percentage = 100 * A/cal #Broadcasting cal from 1x4 to 3x4

print(percentage)

[[94.91525424  0.          2.83140283 90.62170706]
 [ 2.03389831 43.51464435 33.46203346  8.42992624]
 [ 3.05084746 56.48535565 63.70656371  0.9483667 ]]
